name: ingredio
description: "Ingredient scout to make you beautiful."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: 5.2.1
  http: 1.5.0
  shared_preferences: 2.5.3
  google_fonts: ^5.0.0

  cupertino_icons: ^1.0.8
  
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.1
  flutter_markdown: ^0.7.7+1
  device_info_plus: ^12.3.0
  image_cropper: ^11.0.0
  sass: ^1.97.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  http: 1.5.0

  flutter_lints: ^5.0.0
  test: ^1.26.2
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/terms.md
  fonts:
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf